name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Maven Settings.xml file
      uses: s4u/maven-settings-action@v3.1.0
      with:
         repositories: '[{"id":"github1","url":"https://maven.pkg.github.com/finopsautomation/finops-automation-metadata-services"},{"id":"github2","url":"https://maven.pkg.github.com/finopsautomation/finops-automation-metadata-repository-aws"}]'
         servers: '[{"id":"github1","username":"${{secrets.GH_USERNAME}}","password":"${{secrets.GH_PAT}}"},{"id":"github2","username":"${{secrets.GH_USERNAME}}","password":"${{secrets.GH_PAT}}"}]'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

