name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven Settings.xml file
        uses: s4u/maven-settings-action@v3.1.0
        with:
          repositories: '[{"id":"github1","url":"https://maven.pkg.github.com/finopsautomation/finops-automation-metadata-services"},{"id":"github2","url":"https://maven.pkg.github.com/finopsautomation/finops-automation-metadata-repository-aws"}]'
          servers: '[{"id":"github1","username":"${{secrets.GH_USERNAME}}","password":"${{secrets.GH_PAT}}"},{"id":"github2","username":"${{secrets.GH_USERNAME}}","password":"${{secrets.GH_PAT}}"}]'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
